In [1]:
import numpy as np

Basic Array creation

In [2]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
a = [1,2,3.5]
a

[1, 2, 3.5]

In [4]:
np.array(a)

array([1. , 2. , 3.5])

In [5]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array generation function

In [7]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [8]:
arr = np.zeros((4,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Random Generation function

In [11]:
np.random.rand(10)

array([0.01376538, 0.90017891, 0.05527962, 0.34371999, 0.7030424 ,
       0.56001643, 0.34194975, 0.08353173, 0.62572892, 0.26316873])

In [12]:
np.random.randn(10)

array([ 0.3637571 ,  0.56007846,  1.01530825, -1.1028545 ,  0.17654826,
       -0.23582119,  0.81789232,  0.40055966, -1.22813577,  0.17570639])

In [13]:
np.random.randint(10,20,10)

array([11, 16, 10, 17, 19, 15, 18, 17, 18, 14], dtype=int32)

Array Attributes

In [14]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr.shape

(3, 3)

In [16]:
arr.size

9

In [17]:
arr.dtype

dtype('int64')

Array Methods

In [18]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.min()

np.int64(1)

In [20]:
arr.max()

np.int64(9)

In [21]:
arr.sum()

np.int64(45)

In [22]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [23]:
arr.mean()

np.float64(5.0)

In [24]:
arr.std()

np.float64(2.581988897471611)

In [25]:
arr.argmax()

np.int64(8)

In [26]:
arr.argmin()

np.int64(0)

Reshaping and resizing

In [27]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [28]:

arr = arr.reshape(6,5)

In [29]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])